version: "3.8"
services:
    app:
        build: ./docker/server
        depends_on:
            - redis
        networks:
            - appnetwork
        ports:
            - "3001:3000"
        volumes:
            - type: "bind"
              # update this:
              source: "~/dev/poc/docker-hotreload-nodejs/external-app"
              target: "/src"
              # tsc edits files so this must be false
              # if tsc isn't being used then should be able to put this to true
              read_only: false
networks:
    appnetwork: {}
